/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: command.proto */

#ifndef PROTOBUF_C_command_2eproto__INCLUDED
#define PROTOBUF_C_command_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Pb__Command Pb__Command;
typedef struct _Pb__Package Pb__Package;


/* --- enums --- */


/* --- messages --- */

struct  _Pb__Command
{
  ProtobufCMessage base;
  int64_t timestamp;
  int32_t cmd;
  double x;
  double y;
  int32_t w;
  int64_t color;
};
#define PB__COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb__command__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  _Pb__Package
{
  ProtobufCMessage base;
  int32_t scene;
  int64_t user;
  size_t n_cmd;
  Pb__Command **cmd;
};
#define PB__PACKAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pb__package__descriptor) \
    , 0, 0, 0,NULL }


/* Pb__Command methods */
void   pb__command__init
                     (Pb__Command         *message);
size_t pb__command__get_packed_size
                     (const Pb__Command   *message);
size_t pb__command__pack
                     (const Pb__Command   *message,
                      uint8_t             *out);
size_t pb__command__pack_to_buffer
                     (const Pb__Command   *message,
                      ProtobufCBuffer     *buffer);
Pb__Command *
       pb__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb__command__free_unpacked
                     (Pb__Command *message,
                      ProtobufCAllocator *allocator);
/* Pb__Package methods */
void   pb__package__init
                     (Pb__Package         *message);
size_t pb__package__get_packed_size
                     (const Pb__Package   *message);
size_t pb__package__pack
                     (const Pb__Package   *message,
                      uint8_t             *out);
size_t pb__package__pack_to_buffer
                     (const Pb__Package   *message,
                      ProtobufCBuffer     *buffer);
Pb__Package *
       pb__package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pb__package__free_unpacked
                     (Pb__Package *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Pb__Command_Closure)
                 (const Pb__Command *message,
                  void *closure_data);
typedef void (*Pb__Package_Closure)
                 (const Pb__Package *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor pb__command__descriptor;
extern const ProtobufCMessageDescriptor pb__package__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_command_2eproto__INCLUDED */
