/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: command.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "command.pb-c.h"
void   pb__command__init
                     (Pb__Command         *message)
{
  static const Pb__Command init_value = PB__COMMAND__INIT;
  *message = init_value;
}
size_t pb__command__get_packed_size
                     (const Pb__Command *message)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__command__pack
                     (const Pb__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__command__pack_to_buffer
                     (const Pb__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Command *
       pb__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Command *)
     protobuf_c_message_unpack (&pb__command__descriptor,
                                allocator, len, data);
}
void   pb__command__free_unpacked
                     (Pb__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__point__init
                     (Pb__Point         *message)
{
  static const Pb__Point init_value = PB__POINT__INIT;
  *message = init_value;
}
size_t pb__point__get_packed_size
                     (const Pb__Point *message)
{
  assert(message->base.descriptor == &pb__point__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__point__pack
                     (const Pb__Point *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__point__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__point__pack_to_buffer
                     (const Pb__Point *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__point__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Point *
       pb__point__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Point *)
     protobuf_c_message_unpack (&pb__point__descriptor,
                                allocator, len, data);
}
void   pb__point__free_unpacked
                     (Pb__Point *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__point__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__line__init
                     (Pb__Line         *message)
{
  static const Pb__Line init_value = PB__LINE__INIT;
  *message = init_value;
}
size_t pb__line__get_packed_size
                     (const Pb__Line *message)
{
  assert(message->base.descriptor == &pb__line__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__line__pack
                     (const Pb__Line *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__line__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__line__pack_to_buffer
                     (const Pb__Line *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__line__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Line *
       pb__line__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Line *)
     protobuf_c_message_unpack (&pb__line__descriptor,
                                allocator, len, data);
}
void   pb__line__free_unpacked
                     (Pb__Line *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__line__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__scene__init
                     (Pb__Scene         *message)
{
  static const Pb__Scene init_value = PB__SCENE__INIT;
  *message = init_value;
}
size_t pb__scene__get_packed_size
                     (const Pb__Scene *message)
{
  assert(message->base.descriptor == &pb__scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__scene__pack
                     (const Pb__Scene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__scene__pack_to_buffer
                     (const Pb__Scene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Scene *
       pb__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Scene *)
     protobuf_c_message_unpack (&pb__scene__descriptor,
                                allocator, len, data);
}
void   pb__scene__free_unpacked
                     (Pb__Scene *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__package__init
                     (Pb__Package         *message)
{
  static const Pb__Package init_value = PB__PACKAGE__INIT;
  *message = init_value;
}
size_t pb__package__get_packed_size
                     (const Pb__Package *message)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__package__pack
                     (const Pb__Package *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__package__pack_to_buffer
                     (const Pb__Package *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Package *
       pb__package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Package *)
     protobuf_c_message_unpack (&pb__package__descriptor,
                                allocator, len, data);
}
void   pb__package__free_unpacked
                     (Pb__Package *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__package__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__key_frame__init
                     (Pb__KeyFrame         *message)
{
  static const Pb__KeyFrame init_value = PB__KEY_FRAME__INIT;
  *message = init_value;
}
size_t pb__key_frame__get_packed_size
                     (const Pb__KeyFrame *message)
{
  assert(message->base.descriptor == &pb__key_frame__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__key_frame__pack
                     (const Pb__KeyFrame *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__key_frame__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__key_frame__pack_to_buffer
                     (const Pb__KeyFrame *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__key_frame__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__KeyFrame *
       pb__key_frame__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__KeyFrame *)
     protobuf_c_message_unpack (&pb__key_frame__descriptor,
                                allocator, len, data);
}
void   pb__key_frame__free_unpacked
                     (Pb__KeyFrame *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__key_frame__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__page_index__init
                     (Pb__PageIndex         *message)
{
  static const Pb__PageIndex init_value = PB__PAGE_INDEX__INIT;
  *message = init_value;
}
size_t pb__page_index__get_packed_size
                     (const Pb__PageIndex *message)
{
  assert(message->base.descriptor == &pb__page_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__page_index__pack
                     (const Pb__PageIndex *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__page_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__page_index__pack_to_buffer
                     (const Pb__PageIndex *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__page_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__PageIndex *
       pb__page_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__PageIndex *)
     protobuf_c_message_unpack (&pb__page_index__descriptor,
                                allocator, len, data);
}
void   pb__page_index__free_unpacked
                     (Pb__PageIndex *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__page_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__header__init
                     (Pb__Header         *message)
{
  static const Pb__Header init_value = PB__HEADER__INIT;
  *message = init_value;
}
size_t pb__header__get_packed_size
                     (const Pb__Header *message)
{
  assert(message->base.descriptor == &pb__header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__header__pack
                     (const Pb__Header *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__header__pack_to_buffer
                     (const Pb__Header *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Header *
       pb__header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Header *)
     protobuf_c_message_unpack (&pb__header__descriptor,
                                allocator, len, data);
}
void   pb__header__free_unpacked
                     (Pb__Header *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb__command__field_descriptors[7] =
{
  {
    "shape",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, shape),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__command__field_indices_by_name[] = {
  1,   /* field[1] = cmd */
  5,   /* field[5] = color */
  0,   /* field[0] = shape */
  6,   /* field[6] = user */
  4,   /* field[4] = w */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange pb__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor pb__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Command",
  "Command",
  "Pb__Command",
  "pb",
  sizeof(Pb__Command),
  7,
  pb__command__field_descriptors,
  pb__command__field_indices_by_name,
  1,  pb__command__number_ranges,
  (ProtobufCMessageInit) pb__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__point__field_descriptors[2] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Point, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Point, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__point__field_indices_by_name[] = {
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange pb__point__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pb__point__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Point",
  "Point",
  "Pb__Point",
  "pb",
  sizeof(Pb__Point),
  2,
  pb__point__field_descriptors,
  pb__point__field_indices_by_name,
  1,  pb__point__number_ranges,
  (ProtobufCMessageInit) pb__point__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__line__field_descriptors[4] =
{
  {
    "user",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Line, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Line, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Line, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "points",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Line, n_points),
    offsetof(Pb__Line, points),
    &pb__point__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__line__field_indices_by_name[] = {
  1,   /* field[1] = color */
  3,   /* field[3] = points */
  0,   /* field[0] = user */
  2,   /* field[2] = width */
};
static const ProtobufCIntRange pb__line__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb__line__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Line",
  "Line",
  "Pb__Line",
  "pb",
  sizeof(Pb__Line),
  4,
  pb__line__field_descriptors,
  pb__line__field_indices_by_name,
  1,  pb__line__number_ranges,
  (ProtobufCMessageInit) pb__line__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__scene__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Scene, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resource",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Pb__Scene, resource),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pagecount",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Scene, pagecount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Scene, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__scene__field_indices_by_name[] = {
  3,   /* field[3] = index */
  2,   /* field[2] = pagecount */
  1,   /* field[1] = resource */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange pb__scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb__scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Scene",
  "Scene",
  "Pb__Scene",
  "pb",
  sizeof(Pb__Scene),
  4,
  pb__scene__field_descriptors,
  pb__scene__field_indices_by_name,
  1,  pb__scene__number_ranges,
  (ProtobufCMessageInit) pb__scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__package__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, scene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Package, n_cmd),
    offsetof(Pb__Package, cmd),
    &pb__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lines",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Package, n_lines),
    offsetof(Pb__Package, lines),
    &pb__line__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newScene",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, newscene),
    &pb__scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scenes",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Package, n_scenes),
    offsetof(Pb__Package, scenes),
    &pb__scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__package__field_indices_by_name[] = {
  4,   /* field[4] = cmd */
  5,   /* field[5] = lines */
  6,   /* field[6] = newScene */
  3,   /* field[3] = page */
  2,   /* field[2] = scene */
  7,   /* field[7] = scenes */
  1,   /* field[1] = timestamp */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange pb__package__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor pb__package__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Package",
  "Package",
  "Pb__Package",
  "pb",
  sizeof(Pb__Package),
  8,
  pb__package__field_descriptors,
  pb__package__field_indices_by_name,
  1,  pb__package__number_ranges,
  (ProtobufCMessageInit) pb__package__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__key_frame__field_descriptors[4] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__KeyFrame, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scene",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__KeyFrame, scene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__KeyFrame, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__KeyFrame, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__key_frame__field_indices_by_name[] = {
  0,   /* field[0] = offset */
  2,   /* field[2] = page */
  1,   /* field[1] = scene */
  3,   /* field[3] = timestamp */
};
static const ProtobufCIntRange pb__key_frame__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pb__key_frame__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.KeyFrame",
  "KeyFrame",
  "Pb__KeyFrame",
  "pb",
  sizeof(Pb__KeyFrame),
  4,
  pb__key_frame__field_descriptors,
  pb__key_frame__field_indices_by_name,
  1,  pb__key_frame__number_ranges,
  (ProtobufCMessageInit) pb__key_frame__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__page_index__field_descriptors[3] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__PageIndex, scene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__PageIndex, page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__PageIndex, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__page_index__field_indices_by_name[] = {
  1,   /* field[1] = page */
  0,   /* field[0] = scene */
  2,   /* field[2] = timestamp */
};
static const ProtobufCIntRange pb__page_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__page_index__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.PageIndex",
  "PageIndex",
  "Pb__PageIndex",
  "pb",
  sizeof(Pb__PageIndex),
  3,
  pb__page_index__field_descriptors,
  pb__page_index__field_indices_by_name,
  1,  pb__page_index__number_ranges,
  (ProtobufCMessageInit) pb__page_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__header__field_descriptors[5] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Header, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duration",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Header, duration),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyframes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Header, n_keyframes),
    offsetof(Pb__Header, keyframes),
    &pb__key_frame__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pageindexs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Header, n_pageindexs),
    offsetof(Pb__Header, pageindexs),
    &pb__page_index__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scenes",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Header, n_scenes),
    offsetof(Pb__Header, scenes),
    &pb__scene__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__header__field_indices_by_name[] = {
  1,   /* field[1] = duration */
  2,   /* field[2] = keyframes */
  3,   /* field[3] = pageindexs */
  4,   /* field[4] = scenes */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange pb__header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor pb__header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Header",
  "Header",
  "Pb__Header",
  "pb",
  sizeof(Pb__Header),
  5,
  pb__header__field_descriptors,
  pb__header__field_indices_by_name,
  1,  pb__header__number_ranges,
  (ProtobufCMessageInit) pb__header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
