/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: command.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "command.pb-c.h"
void   pb__command__init
                     (Pb__Command         *message)
{
  static const Pb__Command init_value = PB__COMMAND__INIT;
  *message = init_value;
}
size_t pb__command__get_packed_size
                     (const Pb__Command *message)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__command__pack
                     (const Pb__Command *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__command__pack_to_buffer
                     (const Pb__Command *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Command *
       pb__command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Command *)
     protobuf_c_message_unpack (&pb__command__descriptor,
                                allocator, len, data);
}
void   pb__command__free_unpacked
                     (Pb__Command *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pb__package__init
                     (Pb__Package         *message)
{
  static const Pb__Package init_value = PB__PACKAGE__INIT;
  *message = init_value;
}
size_t pb__package__get_packed_size
                     (const Pb__Package *message)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pb__package__pack
                     (const Pb__Package *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pb__package__pack_to_buffer
                     (const Pb__Package *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pb__package__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Pb__Package *
       pb__package__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Pb__Package *)
     protobuf_c_message_unpack (&pb__package__descriptor,
                                allocator, len, data);
}
void   pb__package__free_unpacked
                     (Pb__Package *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pb__package__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pb__command__field_descriptors[6] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "x",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "w",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, w),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Command, color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__command__field_indices_by_name[] = {
  1,   /* field[1] = cmd */
  5,   /* field[5] = color */
  0,   /* field[0] = timestamp */
  4,   /* field[4] = w */
  2,   /* field[2] = x */
  3,   /* field[3] = y */
};
static const ProtobufCIntRange pb__command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor pb__command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Command",
  "Command",
  "Pb__Command",
  "pb",
  sizeof(Pb__Command),
  6,
  pb__command__field_descriptors,
  pb__command__field_indices_by_name,
  1,  pb__command__number_ranges,
  (ProtobufCMessageInit) pb__command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pb__package__field_descriptors[3] =
{
  {
    "scene",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, scene),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Pb__Package, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Pb__Package, n_cmd),
    offsetof(Pb__Package, cmd),
    &pb__command__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pb__package__field_indices_by_name[] = {
  2,   /* field[2] = cmd */
  0,   /* field[0] = scene */
  1,   /* field[1] = user */
};
static const ProtobufCIntRange pb__package__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor pb__package__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "pb.Package",
  "Package",
  "Pb__Package",
  "pb",
  sizeof(Pb__Package),
  3,
  pb__package__field_descriptors,
  pb__package__field_indices_by_name,
  1,  pb__package__number_ranges,
  (ProtobufCMessageInit) pb__package__init,
  NULL,NULL,NULL    /* reserved[123] */
};
